/**
 * Core domain types shared across every layer of SWARMEXEC.
 *
 * Data flows strictly one direction: Signal -> Intent -> Order -> Fill.
 * Each layer may only narrow/reject what the previous layer produced.
 */

export type Mode = "PAPER" | "TESTNET" | "LIVE_CAPPED" | "LIVE";

export type Side = "BUY" | "SELL";

/** Something a signal source observed in the world. Never trades directly. */
export interface Signal {
  id: string;
  source: string;
  token: string;
  mint: string;
  kind: "NEW_PAIR" | "WHALE_MOVE" | "SENTIMENT_SPIKE" | "PRICE_MOVE";
  observedAt: number;
  payload: Record<string, unknown>;
}

/** What a strategy wants to do. Pure output of a pure function. */
export interface Intent {
  id: string;
  strategyId: string;
  signalId: string;
  token: string;
  mint: string;
  side: Side;
  /** Desired notional size in USD. The risk layer may shrink this. */
  sizeUsd: number;
  maxSlippageBps: number;
  reasoning: string;
  createdAt: number;
  /** SELL intents generated by the position manager for SL/TP are exempt from entry rate limits. */
  isExit?: boolean;
}

export type RiskRejectionReason =
  | "MODE_HALTED"
  | "KILL_SWITCH_ACTIVE"
  | "DAILY_LOSS_CIRCUIT_BREAKER"
  | "MAX_TRADES_PER_HOUR"
  | "MAX_TOTAL_CAPITAL_AT_RISK"
  | "DUPLICATE_SIGNAL"
  | "RUG_CHECK_FAILED"
  | "PRICE_SOURCES_DISAGREE"
  | "STRATEGY_NOT_GRADUATED"
  | "ZERO_SIZE_AFTER_CAPS";

export type RiskDecision =
  | { approved: true; order: Order }
  | { approved: false; reason: RiskRejectionReason; detail: string };

/** An Intent that has passed every hard gate and is ready for execution. */
export interface Order {
  id: string;
  intentId: string;
  strategyId: string;
  token: string;
  mint: string;
  side: Side;
  sizeUsd: number;
  maxSlippageBps: number;
  isExit: boolean;
  createdAt: number;
}

export interface Fill {
  id: string;
  orderId: string;
  token: string;
  mint: string;
  side: Side;
  sizeUsd: number;
  price: number;
  feeUsd: number;
  slippageBps: number;
  mode: Mode;
  txSignature?: string;
  filledAt: number;
}

export interface Position {
  token: string;
  mint: string;
  strategyId: string;
  entryPrice: number;
  sizeUsd: number;
  qty: number;
  openedAt: number;
  stopLossPct: number;
  takeProfitPct: number;
}

/** Everything written to the append-only audit log is one of these. */
export type SwarmEvent =
  | { type: "SIGNAL"; at: number; data: Signal }
  | { type: "INTENT"; at: number; data: Intent }
  | { type: "RISK_DECISION"; at: number; data: RiskDecision & { intentId: string } }
  | { type: "ORDER"; at: number; data: Order }
  | { type: "FILL"; at: number; data: Fill }
  | { type: "POSITION_OPENED"; at: number; data: Position }
  | { type: "POSITION_CLOSED"; at: number; data: Position & { exitPrice: number; pnlUsd: number } }
  | { type: "CIRCUIT_BREAKER_TRIPPED"; at: number; data: { reason: string; dailyPnlUsd: number } }
  | { type: "KILL_SWITCH"; at: number; data: { action: "HALT" | "HALT_AND_EXIT"; triggeredBy: string } }
  | { type: "MODE_BOOT"; at: number; data: { mode: Mode } };
